import fs from 'node:fs';
export const site = JSON.parse(fs.readFileSync(new URL('../config/site.json', import.meta.url), 'utf8'));
export const entity = JSON.parse(fs.readFileSync(new URL('../config/entity.json', import.meta.url), 'utf8'));
export const escape = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function origin(env = process.env) {
  const value = env.SITE_URL || entity.websiteUrl || (env.VERCEL_PROJECT_PRODUCTION_URL ? `https://${env.VERCEL_PROJECT_PRODUCTION_URL}` : 'http://localhost:3000');
  const url = new URL(value);
  if (!['http:', 'https:'].includes(url.protocol) || url.username || url.password || url.pathname !== '/' || url.search || url.hash) throw new Error('SITE_URL must be an http(s) origin with no path, credentials, query, or fragment.');
  return url.origin;
}
export const icons = {
 arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M5 16v5h14v-5"/>',
 check:'<path d="m5 12 4 4L19 6"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 11h18M8 15h2m4 0h2M8 18h2"/>',
 receipt:'<path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 7h6M9 11h6m-6 4h3"/>',heart:'<path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8L12 21l8.8-8.6a5.5 5.5 0 0 0 0-7.8Z"/>',
 folder:'<path d="M3 7V5a2 2 0 0 1 2-2h5l3 4h6a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V7Z"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3Z"/><path d="m8 12 3 3 5-6"/>',
 team:'<circle cx="8" cy="7" r="3"/><path d="M2 21v-3a6 6 0 0 1 12 0v3M16 4a3 3 0 0 1 0 6m2 4a5 5 0 0 1 4 5v2"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M9 21h6"/>',
 sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12 2 2M4 20l2-2M18 6l2-2"/>',history:'<path d="M3 11a9 9 0 1 1 2 7M3 4v7h7m2-4v6l4 2"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',plus:'<path d="M12 5v14M5 12h14"/>',lock:'<rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V6a4 4 0 0 1 8 0v4m-4 5v2"/>'
};
export const icon = (name, cls = '') => `<svg class="icon ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name] || icons.check}</svg>`;
export const brand = () => '<span class="brand-mark" aria-hidden="true">tt</span><span class="brand-name">Tag<span>Team</span></span>';
export const downloadButton = (label='Download the App', cls='') => `<a class="button ${cls}" href="/#download">${icon('download')}${label}</a>`;
export const photo = (cls='', eager=false) => `<img class="${cls}" src="/assets/family-1200.webp" srcset="/assets/family-640.webp 640w, /assets/family-1200.webp 1200w, /assets/family-1536.webp 1536w" sizes="(max-width: 760px) 100vw, 55vw" width="1536" height="1024" alt="Two parents sharing a relaxed moment with their children in a Cape Town park" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async">`;
export const checkList = items => `<ul class="check-list">${items.map(s=>`<li>${icon('check')}<span>${s}</span></li>`).join('')}</ul>`;
export const faq = items => `<div class="faq-list">${items.map(([q,a])=>`<details><summary>${escape(q)}${icon('plus')}</summary><div class="faq-answer"><p>${a}</p></div></details>`).join('')}</div>`;
export function footerCTA() { return `<section class="cta-band"><div class="container cta-inner"><div><p class="eyebrow">A little less admin. A little more family.</p><h2>Your next chapter.<br>A little more together.</h2></div><div>${downloadButton('Download the App','button-light')}<p>7 days free. No credit card required.</p></div></div></section>`; }
export function layout({title, description, path, body, schema=[], noindex=false}) {
  const base=origin(), canonical=base+path;
  const navigation=[['/','Home'],['/about/','About Us'],['/features/','Features'],['/pricing/','Pricing'],['/contact/','Contact Us']];
  const org={'@type':'Organization','@id':base+'/#organization',name:'TagTeam',url:base+'/',email:entity.contactEmail,founder:{'@type':'Person',name:'Juan Julyan'},address:{'@type':'PostalAddress',addressLocality:entity.city,addressCountry:'ZA'}};
  const graph=[org,{'@type':'WebSite','@id':base+'/#website',url:base+'/',name:'TagTeam',publisher:{'@id':base+'/#organization'}},{'@type':'WebPage','@id':canonical+'#webpage',url:canonical,name:title,description,inLanguage:'en-ZA',isPartOf:{'@id':base+'/#website'},dateModified:site.lastUpdated},...schema];
  if(path!=='/'&&!noindex) graph.push({'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:base+'/'},{'@type':'ListItem',position:2,name:title.split(' | ')[0],item:canonical}]});
  const structured=JSON.stringify({'@context':'https://schema.org','@graph':graph}).replace(/</g,'\\u003c');
  const robots=noindex||process.env.VERCEL_ENV==='preview'?'noindex, nofollow':'index, follow, max-image-preview:large';
  return `<!doctype html><html lang="en-ZA"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(title)}</title><meta name="description" content="${escape(description)}"><meta name="robots" content="${robots}"><meta name="theme-color" content="#2454d6"><link rel="canonical" href="${escape(canonical)}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/assets/icon-192.png"><link rel="preload" href="/assets/manrope.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/site.css"><meta property="og:type" content="website"><meta property="og:locale" content="en_ZA"><meta property="og:site_name" content="TagTeam"><meta property="og:title" content="${escape(title)}"><meta property="og:description" content="${escape(description)}"><meta property="og:url" content="${escape(canonical)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${escape(title)}"><meta name="twitter:description" content="${escape(description)}"><script type="application/ld+json">${structured}</script><script defer src="/assets/site.js"></script></head><body><a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="container nav-wrap"><a href="/" class="brand" aria-label="TagTeam home">${brand()}</a><button type="button" class="menu-toggle" aria-expanded="false" aria-controls="main-nav"><span class="menu-lines" aria-hidden="true"></span><span>Menu</span></button><nav id="main-nav" class="main-nav" aria-label="Main navigation">${navigation.map(([href,label])=>`<a href="${href}" ${href===path?'aria-current="page"':''}>${label}</a>`).join('')}${downloadButton('Download the App','nav-download')}</nav></div></header><main id="main">${body}</main><footer class="site-footer"><div class="container"><div class="footer-top"><div class="footer-brand"><a href="/" class="brand" aria-label="TagTeam home">${brand()}</a><p>Two homes. One team.<br>A little more calm for the family you share.</p></div><div><h2>Explore</h2><nav aria-label="Footer navigation"><a href="/about/">About Us</a><a href="/features/">Features</a><a href="/pricing/">Pricing</a><a href="/contact/">Contact Us</a></nav></div><div><h2>Made for real life</h2><p>Created in Cape Town.<br>Built around children, and the parents who love them.</p><a class="text-link" href="/#download">Download for Android ${icon('arrow')}</a></div></div><div class="footer-bottom"><span>© ${new Date(site.lastUpdated).getUTCFullYear()} TagTeam. All rights reserved.</span><div><a href="/privacy/">Privacy Policy</a><a href="/terms/">Terms &amp; Conditions</a></div></div></div></footer></body></html>`;
}
