import {site,entity} from '../lib/site.mjs';
const support=`<a href="mailto:${entity.contactEmail}">${entity.contactEmail}</a>`;
const childrenAct='<a href="https://www.gov.za/documents/childrens-act" target="_blank" rel="noopener noreferrer">Children’s Act, sections 33–34</a>';
export const faqGroups=[
 {id:'getting-started',name:'Getting started',icon:'team',items:[
 ['what-is-tagteam','What is TagTeam?','TagTeam is a co-parenting app for two connected parents. It brings shared events, care routines, expenses, medical history and family documents into one place. It was created in Cape Town by Juan Julyan, a father of two.'],
 ['who-is-it-for','Who is TagTeam for?','TagTeam is for parents sharing the day-to-day care of their children. It welcomes different family backgrounds, cultures and genders. You choose the routine and expense split that fit your family and any agreements that apply to you.'],
 ['both-parents','Do both parents need their own account?','Yes. Each parent uses a separate email-verified account and their own phone. One parent creates the family and invites the other. Both need active trial or paid access and a successful sync to exchange new shared information.'],
 ['connect-family','How do I connect with my co-parent?','Create your account, verify your email and activate it. One parent creates a family using the other parent’s email address, then shares the invitation code. The other parent signs up with that email and uses the code to join. Invitations are single-use and expire after seven days.'],
 ['availability','Where can I download TagTeam?',`${site.appStoreUrl||site.googlePlayUrl?'Available store listings are linked':'App Store and Google Play listings will be linked'} on our <a href="/download/">download page</a>. A store marked “Coming soon” does not have an available download link yet. ${site.publicServiceReady?'Public registration is open.':'Public registration is preparing to launch.'}`],
 ['iphone','Is TagTeam available for iPhone? ',site.appStoreUrl?'The App Store link is available on our download page. Check that listing for supported devices and the latest release details.':'An iPhone release is not currently available. The App Store space on the download page is reserved for its future listing. The supplied current app release is Android.'],
 ['family-size','Can children, grandparents or a third parent have access?','This release supports two parent accounts in one family per account. You can add your children’s details to that family, but children, grandparents, professionals and other caregivers do not have separate access accounts in this release.']
 ]},
 {id:'schedules',name:'Schedules & routines',icon:'calendar',items:[
 ['care-routines','Which care routines can we use?','Choose workweek/weekends, alternating weeks, 2/2/3, two weeks/two weeks or month/month. You can also customise morning and evening care periods. The app records your agreed routine; it does not decide which arrangement is right for your children.'],
 ['recurring-events','Can I add recurring events and school holidays?','Yes. You can add once-off, date-range and recurring events, with descriptions and attachments. Use date ranges for holidays or trips and review each event’s dates, recurrence and care periods before submitting it.'],
 ['change-plans','What happens when our plans change?','Add an event and request the other parent’s confirmation. Confirmed events can override the selected dates and morning or evening periods in your normal care routine. When a routine-changing event is deleted after approval, the standard routine returns.'],
 ['views','Can I see upcoming and past events?','Yes. Events and medical history have calendar and list views. You can move between upcoming and past records, return to today and review the event details. The daily overview also shows today and tomorrow’s events.'],
 ['parenting-plan','Does TagTeam replace a parenting plan or court order?',`No. TagTeam organises information and records responses; an in-app confirmation does not automatically change a parenting plan or court order. South African parenting plans have legal formalities, including being written and signed. Get appropriate advice about your own arrangements. See the ${childrenAct}.`],
 ['time-zone','Which time zone does the care routine use?','Care routines and scheduled evening briefings use South African time. If a parent travels or lives in a different time zone, agree the actual handover time clearly and check it against the app’s South African schedule.']
 ]},
 {id:'expenses',name:'Expenses & payments',icon:'receipt',items:[
 ['split-expenses','Can we split costs differently from 50/50?','Yes. Set your agreed expense ratio for the family. TagTeam calculates each share using the saved expense and ratio. It does not decide which expenses are reasonable, legally payable or covered by your parenting agreement.'],
 ['scan-receipts','How does receipt capture work?','Upload or photograph the receipt, check the detected total and add a reason, category and due date. Receipt recognition can misread a total, so always review it before saving. The receipt stays with the expense record.'],
 ['payment-confirmation','How do we confirm that an expense was paid?','The paying parent marks the expense as paid. The receiving parent then confirms receipt. Until that confirmation, review the payment’s pending status. These actions record what each parent reports; they do not verify a bank transfer.'],
 ['transfer-money','Does TagTeam transfer money between parents?','No. Parents make payments separately using their chosen payment method. TagTeam calculates shares, tracks outstanding amounts and records payment confirmations. App subscriptions are separate from family expense reimbursements.'],
 ['expense-reports','Can I download an expense report?','Yes. Contribution summaries include charts and a month/category breakdown. View 3, 6 or 12 months, or all time, and export a PDF containing the chart and underlying data. Keep exported reports somewhere secure.'],
 ['contributions','What do the contribution charts measure?','They reflect each parent’s paid contribution, rather than simply who first uploaded an expense. Until reimbursement is confirmed, the unsettled amount remains allocated to the parent who uploaded it. Use the unsettled toggle to control the report’s scope.'],
 ['maintenance','Does an expense entry change a maintenance obligation?','No. A saved expense, calculated share or payment confirmation does not by itself determine or change a legal maintenance obligation. Follow the agreement or order that applies to you and get professional advice if you disagree about what is payable.']
 ]},
 {id:'privacy',name:'Documents & privacy',icon:'shield',items:[
 ['shared-data','Who can see our family’s information?','Shared events, expenses, receipts, children’s details, medical records and documents are available to both connected parents. Other families should not have access. Authorised service operators may handle data for support, security and legal duties, as described in the <a href="/privacy/">Privacy Policy</a>.'],
 ['encryption','Is TagTeam end-to-end encrypted?','No. The Android release encrypts records and files in its private app storage and uses encrypted network connections. Cloud access is checked against the signed-in account and family. Service operators and processors can handle information for the purposes described in the Privacy Policy.'],
 ['file-types','Which documents can I upload?','The current app accepts PDF, JPG and PNG files up to 10 MB each. Shared documents can include medical aid information, birth certificates and other relevant family records. Only upload information you are entitled to share with the connected parent.'],
 ['medical-changes','Can either parent change or delete medical records?','Either parent can propose an addition or edit. The other parent reviews it and can confirm or return an amended proposal. Saved medical details change after confirmation. Deletion also requires confirmation; supporting proposal or activity history may remain.'],
 ['screen-lock','Why does Documents ask for my screen lock?','The Android Documents section uses the phone’s screen lock to help protect access. TagTeam does not receive your fingerprint or face template. Files you explicitly export are ordinary files outside the app’s protected storage.'],
 ['location','Can my co-parent see my location?','TagTeam does not share your weather location with your co-parent or provide continuous location tracking. Approximate location is optional and used for weather requests. You can change or remove the saved location in Family and control permission in Android Settings.'],
 ['delete-data','How do I request a data export or account deletion?',`Contact ${support} from your account email. We may verify your identity and consider legal retention requirements and the rights of the other parent and children. Deleting an account cannot erase files someone has already exported. Cancelling a subscription and deleting an account are separate requests.`],
 ['popia','How do I raise a privacy or POPIA concern?',`Send your concern or access, correction or deletion request to ${support}. Our <a href="/privacy/">Privacy Policy</a> explains data handling and the limits on shared-record deletion. You may also complain to the <a href="https://inforegulator.org.za/complaints/" target="_blank" rel="noopener noreferrer">Information Regulator</a> about alleged unlawful processing.`]
 ]},
 {id:'billing',name:'Trial & subscriptions',icon:'calendar',items:[
 ['cost','How much does TagTeam cost?',`Try TagTeam for ${site.trialDays} days free, then R${site.monthlyPrice} per month per user if you choose to subscribe. Two subscribed parents pay R${site.monthlyPrice*2} per month in total. Each parent has their own account and subscription. <a href="/pricing/">See pricing</a>.`],
 ['trial-start','When does my free trial start?',`The ${site.trialDays}-day offer starts when you activate your email-verified account by entering your name and accepting the app’s terms and privacy notice after launch. Each parent has their own trial dates. Simply visiting the website does not start a trial.`],
 ['card','Do I need a credit card for the trial?','No. The free trial requires no payment details and does not automatically turn into a paid subscription. You must explicitly choose and authorise a subscription to continue with paid access.'],
 ['trial-end','What happens when my trial ends?','New server access, shared updates and file downloads pause for that account until paid access is active. Support and subscription controls remain available. The other parent’s active subscription is unaffected, but both need active access to exchange new updates.'],
 ['subscribe','How do I subscribe after the trial?','The current Android app uses Family → Subscription to open Payfast checkout when you choose to subscribe. Review the amount and renewal terms before authorising payment. Check the released store listing and checkout for the payment options applicable to that version.'],
 ['cancel','Can I cancel monthly renewal?',`Yes. For the current Payfast subscription, open Family → Subscription and cancel renewal before the next billing date. Wait for confirmation. Paid access normally continues until the paid period ends. If cancellation fails or you cannot sign in, contact ${support}. Uninstalling the app does not cancel billing.`],
 ['refunds','What if I have a payment problem or need a refund?',`Email ${support} with your account email, payment date and payment reference. Do not send card numbers or passwords. Refund requests are considered under applicable law and the circumstances. Payment confirmation can take time; returning from checkout alone does not confirm that the service received payment.`]
 ]},
 {id:'help',name:'Everyday help',icon:'bell',items:[
 ['offline','Can I use TagTeam offline?','During an active trial or paid period, previously synced records and supported queued changes can be available offline. Accounts, new shared updates, file downloads and billing need internet access. An offline copy can be out of date, so check that important changes have synced.'],
 ['notifications','Why did I miss a reminder?','Check internet access, Android notification permissions, Do Not Disturb and battery restrictions. Force-stopping the app can also prevent alerts. Delivery is affected by device settings and connectivity, so keep separate reminders for time-critical appointments or handovers.'],
 ['weather','Can I use the app without location or weather?','Yes. Weather is optional. You can decline location access or remove your saved weather location in Family. Your schedules, expenses and shared family records do not require a weather location. Forecasts may be delayed or unavailable.'],
 ['new-phone','What should I do when I change phones?','Sign in with the same account on a supported phone and sync with an active trial or subscription and internet access. Cloud-synced records can be retrieved. Finish syncing queued changes on the old phone first; local-only changes and exported files do not automatically transfer.'],
 ['contact-support','How do I get help?',`Use <a href="/contact/">Contact Us</a>, email ${support}, or open Family → Support in the Android app. In-app support remains available after access expires. Include the app version and a brief description, but leave out children’s medical details, identity numbers and passwords.`]
 ]}
].map(group=>({...group,items:group.items.map(([id,q,a])=>({id,q:q.trim(),a}))}));
export const allFaqs=faqGroups.flatMap(group=>group.items);
export const selectFaqs=ids=>ids.map(id=>allFaqs.find(item=>item.id===id));
export const homeFaq=selectFaqs(['what-is-tagteam','both-parents','cost','availability','shared-data']);
export const pricingFaq=selectFaqs(['trial-start','card','trial-end','subscribe','cancel','refunds']);
